import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  docs: [
    "Intro",
    "Change_Log",
    "Reference",
    {
      type: "category",
      label: "Quickstart",
      items: ["quick_start/Overview_of_Apps", "quick_start/Getting_Started"],
    },
    {
      type: "category",
      label: "Interactions",
      items: [
        "interactions/Overview",
        "interactions/Receiving_and_Responding",
        "interactions/Application_Commands",
        "interactions/Message_Components",
      ],
    },
    {
      type: "category",
      label: "Resources",
      items: [
        "resources/Application",
        "resources/Application_Role_Connection_Metadata",
        "resources/Audit_Log",
        "resources/Auto_Moderation",
        "resources/Channel",
        "resources/Emoji",
        "resources/Guild",
        "resources/Guild_Scheduled_Event",
        "resources/Guild_Template",
        "resources/Invite",
        "resources/Poll",
        "resources/Stage_Instance",
        "resources/Sticker",
        "resources/User",
        "resources/Voice",
        "resources/Webhook",
      ],
    },
    {
      type: "category",
      label: "Topics",
      items: [
        "topics/Certified_Devices",
        "topics/Community_Resources",
        "topics/Gateway",
        "topics/Gateway_Events",
        "topics/OAuth2",
        "topics/Opcodes_and_Status_Codes",
        "topics/Permissions",
        "topics/RPC",
        "topics/Rate_Limits",
        "topics/Teams",
        "topics/Threads",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [
        "tutorials/Configuring_App_Metadata_for_Linked_Roles",
        "tutorials/Developing_a_User_Installable_App",
        "tutorials/Hosting_on_Cloudflare_Workers",
        "tutorials/Upgrading_to_Application_Commands",
      ],
    },
    {
      type: "category",
      label: "Best Practices",
      items: ["best_practices/Crafting_your_App_Directory_Product_Page"],
    },
    {
      type: "category",
      label: "Monetization",
      items: [
        "monetization/Overview",
        "monetization/App_Subscriptions",
        "monetization/One-Time_Purchases",
        "monetization/Managing_Your_Store",
        "monetization/SKUs",
        "monetization/Entitlements",
      ],
    },
    {
      type: "category",
      label: "Activities",
      items: [
        "activities/Overview",
        "activities/How_Activities_Work",
        "activities/Building_An_Activity",
        "activities/Development_Guides",
        "activities/Design_Patterns",
      ],
    },
    {
      type: "category",
      label: "Developer Tools",
      items: ["developer_tools/Embedded_App_SDK"],
    },
    {
      type: "category",
      label: "Rich Presence",
      items: [
        "rich_presence/How_To",
        "rich_presence/Best_Practices",
        "rich_presence/Launch_Checklist",
        "rich_presence/FAQ",
      ],
    },
    {
      type: "category",
      label: "Game SDK",
      items: [
        "game_sdk/Getting_Started",
        "game_sdk/Discord",
        "game_sdk/Achievements",
        "game_sdk/Activities",
        "game_sdk/Applications",
        "game_sdk/Discord_Voice",
        "game_sdk/Images",
        "game_sdk/Lobbies",
        "game_sdk/Networking",
        "game_sdk/Overlay",
        "game_sdk/Relationships",
        "game_sdk/Storage",
        "game_sdk/Store",
        "game_sdk/Users",
      ],
    },
    {
      type: "category",
      label: "Policies and Agreements",
      items: [
        "policies_and_agreements/Developer_Policy",
        "policies_and_agreements/Developer_Terms_of_Service",
        "policies_and_agreements/Monetization_Policy",
      ],
    },
  ],
};

export default sidebars;
