name: Slash Commands Bug Report
description: A bug has been found in Discord's Slash Commands and Interactions.
labels: ["bug", "slash commands"]
body:
  - type: markdown
    attributes:
      value: "Before opening a new issue, please search existing issues:  https://github.com/discord/discord-api-docs/issues?q=is%3Aissue+label%3A%22slash+commands%22"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide clear and concise steps for us to reliably reproduce this issue.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What is the behavior you expect to occur that is not?
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: What is the behavior you are currently seeing instead?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Provide a screenshot and/or video demonstrating the issue being experienced.
    validations:
      required: false
  - type: textarea
    id: information
    attributes:
      label: Client and System Information
      description: What is the browser/library/client you are using? What operating system and version?
    validations:
      required: true
