// AUTOGENERATED BY tools/icons/generate-icons.js: DO NOT MODIFY DIRECTLY

export const ChatIcon = (props) => (<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none"><path fill="currentColor" d="M12 22a10 10 0 1 0-8.45-4.64c.13.19.11.44-.04.61l-2.06 2.37A1 1 0 0 0 2.2 22H12Z" /></svg>);