// AUTOGENERATED BY tools/icons/generate-icons.js: DO NOT MODIFY DIRECTLY

export const PlayIcon = (props) => (<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none"><path fill="currentColor" d="M9.25 3.35C7.87 2.45 6 3.38 6 4.96v14.08c0 1.58 1.87 2.5 3.25 1.61l10.85-7.04a1.9 1.9 0 0 0 0-3.22L9.25 3.35Z" /></svg>);